---
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format

# should be replaced in the future ref https://github.com/astral-sh/ruff/issues/458
- repo: https://github.com/jsh9/pydoclint
  rev: 0.5.9
  hooks:
  - id: pydoclint

- repo: https://github.com/Yelp/detect-secrets
  # for new repo init run: `detect-secrets scan > .secrets.baseline`
  rev: v1.5.0
  hooks:
  - id: detect-secrets
    args: [--baseline, .secrets.baseline]
    exclude: .*/tests/.*
    additional_dependencies: [gibberish-detector]

# should be replaced in the future ref https://github.com/astral-sh/ruff/issues/3792
- repo: https://github.com/asottile/blacken-docs
  rev: 1.19.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==24.10.0]

- repo: local
  hooks:
  - id: mypy
    name: Run mypy
    entry: python -m mypy --install-types --non-interactive --cache-dir=.mypy_cache/ src/
    language: system
    types: [python]
    pass_filenames: false

- repo: https://github.com/pappasam/toml-sort
  rev: v0.23.1
  hooks:
  - id: toml-sort-fix
    args: [--trailing-comma-inline-array]

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args: [--mapping=2, --sequence=2, --offset=0]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: \.(svg)$
  - id: check-merge-conflict
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.3
  hooks:
  - id: check-dependabot
  - id: check-github-workflows
