repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*/tests/.*

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: local
    hooks:
    -   id: mypy
        name: Run mypy
        entry: python -m mypy src/
        language: system
        types: [python]
        pass_filenames: false

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        additional_dependencies: [
            'darglint~=1.8.1',
            'flake8-absolute-import~=1.0',
            'flake8-blind-except~=0.2.1',
            'flake8-builtins~=2.0.1',
            'flake8-cognitive-complexity==0.1.0',
            'flake8-comprehensions~=3.10.0',
            'flake8-docstrings~=1.6.0',
            'flake8-logging-format~=0.8.1',
            'flake8-mutable~=1.2.0',
            'flake8-print~=5.0.0',
            'flake8-printf-formatting~=1.1.0',
            'flake8-pytest-style~=1.6.0',
            'flake8-quotes~=3.3.1',
            'flake8-tuple~=0.4.1',
            'pep8-naming~=0.13.2'
        ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements

-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        pass_filenames: false
        args: [-c, setup.cfg]
