---
name: CI
on:
  pull_request:
  push:
    branches: [master]

concurrency:  # https://stackoverflow.com/questions/66335225#comment133398800_72408109
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write  # codecov/codecov-action
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Pip cache
      uses: actions/cache@v4
      with:
        save-always: true
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements/*.txt') }}

    - name: Pre-commit cache
      uses: actions/cache@v4
      with:
        save-always: true
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ matrix.python-version }}-${{ hashFiles('**/requirements/ci.txt') }}-${{ hashFiles('.pre-commit-config.yaml')
          }}

    - name: Install
      run: |
        pip install -U pip setuptools wheel
        make install

    - name: Lint
      if: matrix.python-version == '3.13'
      run: make lint

    - name: Test
      run: make test

    - name: Docs
      if: matrix.python-version == '3.13'
      run: SPHINXOPTS=-W make builddocs

    - uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        use_oidc: true
